<div class="pricetable"><div class="pricetable-inner">
	<?php foreach((array) $table as $i => $column) : ?>
		<div class="<?php print implode(' ', $column['classes']) ?>" style="width:<?php print $column['width'] ?>%">
			<div class="pricetable-column-inner">
				<div class="pricetable-header">
					<h3 class="pricetable-name"><?php print $column['title'] ?></h3>
					<h4 class="pricetable-price"><?php print $column['price'] ?></h4>
					<p><?php print $column['detail'] ?></p>
				</div>
				
				<div class="features">
					<?php if(!empty($column['features'])) : ?>
						<?php foreach($column['features'] as $j => $feature) : ?>
							<div class="pricetable-feature <?php print $j == 0 ? 'pricetable-first' : '' ?>">
								<?php print $feature['title'] ?>
								<?php if(!empty($feature['sub'])) : ?>
									<small><?php print $feature['sub'] ?></small>
								<?php endif; ?>
							</div>
						<?php endforeach ?>
					<?php endif; ?>
				</div>
				
				<div class="pricetable-button-container">
					<a href="<?php print empty($column['url']) ? '#' : $column['url'] ?>">
						<span class="pricetable-gradient"><span class="pricetable-noise"><?php print empty($column['button']) ? __('Select', 'pricetable') : $column['button'] ?></span></span>
					</a>
				</div>
				
			</div>
		</div>
	<?php endforeach ?>
	
	
	<div class="pricetable-clear"></div>
</div></div>