<div class="wrap about-wrap">
	<h1>Thanks for Using Price Table</h1>
	<div class="about-text">
		I hope you enjoy using it, as much as I enjoyed creating it.
		Follow me if you'd like to stay up to date with the free themes and plugins I create.
		Your support means a lot!
	</div>
	<div class="pricetable-badge">
		<div class="icon"></div>
		<h3>Pricetable Plugin v<?php print $info['Version'] ?></h3>
	</div>
	
	<div class="siteorigin-follow">
		<div class="twitter">
			<div class="follow-wrapper">
				<a href="https://twitter.com/SiteOrigin" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @SiteOrigin</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
		</div>
		
		<div class="facebook">
			<div class="follow-wrapper">
				<iframe src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fsiteorigin&amp;width=292&amp;height=62&amp;colorscheme=light&amp;show_faces=false&amp;border_color&amp;stream=false&amp;header=false&amp;appId=112892270509" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:62px;" allowTransparency="true"></iframe>
			</div>
		</div>
	</div>

	<p>
		If you need help with the plugin, give our <a href="http://siteorigin.com/docs/pricetable/">price table documentation</a> a read.
		If you ever get really stuck, then our free <a href="http://siteorigin.com/forum/">support forums</a> are a great place to get answers to your questions.
	</p>
</div> 